# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Only use the `python3` binary to get the version.
[python]
python_binary = "python3"

# Disable git status too
[git_status]
disabled = true
