on: [push, pull_request]

jobs:
  lines:
    name: Less than 33 lines
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check < 33 lines
        run: if [ $(wc -l .*c* | sed -n 's/.* \([^ ]*\) total.*/\1/p') -ge 33 ]; then exit 1; fi
